apiVersion: v1
kind: Service
metadata:
  name: goapp-test-kustomize-service
spec:
  selector:
    app: goapp-test-kustomize
  ports:
    - protocol: TCP
      port: 80           # The port exposed by the service (can be different)
      targetPort: 5000 
  type: ClusterIP