apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goapp-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL:  https://github.com/miriamdomingo-next/goapp-test-argocd
    #targetRevision: main - Asume esta o develop
    path: manifest/goapp-test/
  destination:
    server: https://kubernetes.default.svc
    namespace: goapp-test # Better to use a proper separated namespace
  syncPolicy:
    syncOptions:
    - CreateNamespace=true #si ya existe no lo crea
    automated:
      selfHeal: true
      prune: true
      enabled: true

