# KUSTOMIZE OVERLAYS/DEV
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: goapp-test-kustomize-deployment
    spec:
      replicas: 3
      template:
        spec:
          containers:
          - name: goapp-test-kustomize-container  # You need to specify the container name
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
  target:
    kind: Deployment
    name: goapp-test-kustomize-deployment